appName: frontend
replicaCount: 2

container:
  image:
    repository: "nguyentankdb17/microserviceapp_frontend"
    tag: 1.0.0
  imagePullPolicy: IfNotPresent
  port: 80
  containerEnvVars:
  - name: ENV1
    value: "value1"
  - name: ENV2
    value: "value2"

service:
  type: ClusterIP
  port: 80
  nodePort: 31000


livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 5
