apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName}}
spec:
  selector:
    app:  {{ .Values.appName}}
  type:  {{ .Values.service.type}}
  ports:
  - protocol: TCP
    port:  {{ .Values.service.port}}
    targetPort:  {{ .Values.container.port}}
    nodePort:  {{ .Values.service.nodePort}}
