apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName}}
spec:
  selector:
    app:  {{ .Values.appName}}
  type:  {{ .Values.serviceType}}
  ports:
  - protocol: TCP
    port:  {{ .Values.servicePort}}
    targetPort:  {{ .Values.containerPort}}
    nodePort:  {{ .Values.nodePort}}